services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: xdatadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1709
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./xdata-web/backend
    environment:
      XDATA_DB_HOST: db
      XDATA_DB_PORT: 5432
      XDATA_DB_NAME: xdatadb
      XDATA_DB_USER: postgres
      XDATA_DB_PASS: 1709
      HIBERNATE_DDL_AUTO: update
      XDATA_SMTSOLVER: /usr/bin/z3
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build: ./xdata-web/frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
