spring.datasource.url=jdbc:postgresql://${databaseIP:localhost}:${databasePort:5432}/${databaseName:xdatadb}
spring.datasource.username=${existingDatabaseUser:postgres}
spring.datasource.password=${existingDatabaseUserPasswd:1709}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# XData Spezifische Pfade
xdata.smtsolver=${smtsolver:/usr/local/bin/z3}
xdata.smtargs=-smt2

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.repair-on-migrate=true
spring.flyway.validate-on-migrate=false
xdata.z3.lib-path=${z3LibPath:/usr/local/lib}
xdata.homeDir=${homeDir:/tmp}
xdata.dataDir=${dataDir:/tmp}
xdata.databaseIP=${databaseIP:localhost}
xdata.databasePort=${databasePort:5432}
xdata.databaseName=${databaseName:xdatadb}
xdata.databaseUsername=${existingDatabaseUser:postgres}
xdata.databasePassword=${existingDatabaseUserPasswd:1709}

# Test Database (für die Generierung)
xdata.test.db.user=${testDatabaseUser:testuser}
xdata.test.db.password=${testDatabaseUserPasswd:Testuser@123}
