# The example file to set the properties if one desires to use XData-Datagen without web interface.
# The variables declared below are to be replaced by the credentials one desire to use while working on XData 

#database type to test student queries 

tempDatabaseType = PostgreSQL

#name of the database to be used
databaseName=xdata2021

#database user name- 
existingDatabaseUser=xdatauser
#password
existingDatabaseUserPasswd=Xdatauser@123



testDatabaseUser=testuser
testDatabaseUserPasswd=Testuser@123


# Address of database server
databaseIP=127.0.0.1
#postgresql port
databasePort=5432


#Scratch directory 
homeDir=/tmp
testDir=/tmp




smtsolver=/usr/bin/z3
smtargs= -smt2


logFile=/tmp/XData.log

queries=queries
dataset=dataset




base=/tmp
mutants=mutants
sample=sample

logLevel=INFO

tempJoins=true
cntFlag = true
existsUnrollFlag = true
sampleDataJson = false
tempJoins=true
cntFlag = true
existsUnrollFlag = true
isEnumInt = false
enumArrayIndex = enum_int
enumIndexVar = v
outerSQ = true
regressDS0 = false
primarykey = 1
project = true

printSQL = false
printDir = /home/parismita/texttosql/gpt4/tmp

