#name of the database to be used; created by the default postgresql script, change if you 
# want to create your own database name
tempDatabaseType = PostgreSQL
databaseName=xdatadb

#database user name- 
existingDatabaseUser=xdatauser
#password
existingDatabaseUserPasswd=Xdatauser@123

testDatabaseUser=testuser
testDatabaseUserPasswd=Testuser@123



# Address of database server; update this if your database is not listening on localhost port 5432
databaseIP=localhost
databasePort=5432

#Path to SMT Solver; update it to the location where you will be installing the cvc3 executable
smtsolver=/usr/bin/z3
smtargs= -smt2 

#Scratch directory; for temporary files Leave these as /tmp preferably
homeDir=/tmp


#Deprecated - directory of scripts; created temporarily for application testing
#scriptsDir=/home/divya/Desktop/pooja-test/xdata-web


#directory for xml files created temporariliy for application testing 
dataDir=/tmp


#Consumer Auth Key for LTI integration; needed only if you are integrating with a learning management
# system such as moodle, blackboard or webct

## To be moved to DB
consumerAuthKey=YourLTIConsumerAuthKey


#Secret key for LTI Integration
## To be moved to DB
secretKey=YourSecretKeyHere


#Call back URL of the LTI system to upload marks
callBackURL=


# Xdata URL expected for OAUTH authentication from LMS  
# Set URL of tool.jsp as accessible by LMS

XDataUrlFromLMS =  

logFile=/tmp/XData.log
logLevel=INFO
 

#Default password for admin login
adminPassword = admin

tempJoins=true

calledFromApplicationTester=false


#name of the database to be used
databaseName=xdatadb

#database user name- 
existingDatabaseUser=xdatauser
#password
existingDatabaseUserPasswd=Xdatauser@123
#CREATE USER xdatauser WITH PASSWORD 'Xdatauser@123';
#CREATE USER testuser WITH PASSWORD 'Testuser@123';

#test database for creating test tables (not required for parsing)
#for mysql
#testDatabaseUser=testing
#testDatabaseUserPasswd=Testing@123
#for postgresql
testDatabaseUser=testuser
testDatabaseUserPasswd=Testuser@123


# Address of database server
databaseIP=127.0.0.1
#postgresql port
databasePort=5432
#mysql port
#databasePort=3306

#Scratch directory 
homeDir=/tmp
testDir=/tmp

smtsolver=/home/sunanda/xdata-count/XData-DataGen/Z3files/z3
smtargs= -smt2


logFile=/tmp/XData.log

queries=queries
dataset=dataset

mutants=mutants
sample=sample


logLevel=INFO

tempJoins=true
cntFlag = true
existsUnrollFlag = true
sampleDataJson = false
tempJoins=true
cntFlag = true
existsUnrollFlag = true
isEnumInt = false
enumArrayIndex = enum_int
enumIndexVar = v
outerSQ = true
regressDS0 = false
primarykey = 1
project = true

printSQL = false
printDir = /home/parismita/texttosql/gpt4/tmp

base=/tmp

	
