#name of the database to be used; created by the default postgresql script, change if you 
# want to create your own database name
databaseName=xdatadb

#database user name- 
existingDatabaseUser=xdatauser
#password
existingDatabaseUserPasswd=Xdatauser@123


# Address of database server; update this if your database is not listening on localhost port 5432
databaseIP=localhost
databasePort=5432

#Path to SMT Solver; update it to the location where you will be installing the cvc3 executable
smtsolver=/usr/local/bin/z3


#Scratch directory; for temporary files Leave these as /tmp preferably
homeDir=/home/abhishek/Documents/mtp/xdata_web/scratch/


#Deprecated - directory of scripts; created temporarily for application testing
scriptsDir=/home/abhishek/Documents/mtp/xdata_web/scripts/


#directory for xml files created temporariliy for application testing 
dataDir=/home/abhishek/Documents/mtp/xdata_web/data/


#Consumer Auth Key for LTI integration; needed only if you are integrating with a learning management
# system such as moodle, blackboard or webct

## To be moved to DB
consumerAuthKey=YourLTIConsumerAuthKey


#Secret key for LTI Integration
## To be moved to DB
secretKey=YourSecretKeyHere


#Call back URL of the LTI system to upload marks
callBackURL=


# Xdata URL expected for OAUTH authentication from LMS  
# Set URL of tool.jsp as accessible by LMS

XDataUrlFromLMS =  

logFile=/home/abhishek/Documents/mtp/xdata_web/XData
logLevel=INFO
 

#Default password for admin login
adminPassword = admin

tempJoins=false

calledFromApplicationTester=false

